version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/compile"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/publish"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/release"
    schedule:
      interval: "monthly"
