name: mMojo release
description: compile a Smallworld product into a mMojo and publish it
author: krn-sebastiaan
branding:
  icon: package
  color: blue

inputs:
  krn-core-version:
    default: 0.4.0+20240221-0755
    required: false
    type: string
  build-xml-path:
    default: build.xml
    required: false
    type: string
  build-arguments:
    default: ''
    required: false
    type: string
  mmojo-name:
    default: ${{ github.event.repository.name }}
    required: false
    type: string
  gpg-passphrase:
    required: true
    type: string
  publish-repository:
    required: true
    type: string
  repository-name:
    required: true
    type: string
  github-token:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: 'true'
        fetch-depth: 0
    - name: Checkout publish repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.publish-repository }}
        token: ${{ inputs.github-token }}
        path: mmojo-store
        lfs: true
    - name: Install SW Core, MUnit and KRN Core
      uses: krn-sebastiaan/krn-core@main
      with:
        gpg-passphrase: ${{ inputs.gpg-passphrase }}
        krn-core-version: ${{ inputs.krn-core-version }}
    - name: Create mMojo
      run: ant -f ${{ inputs.build-xml-path }} make_mojo ${{ inputs.build-arguments }}
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        KRN_REPOSITORY_FILE: "${{ github.workspace }}/mmojo-store/repositories.xml"
    - name: Upload mMojo
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.mmojo-name }}
        path: ${{ inputs.mmojo-name }}*.jar
        if-no-files-found: error
    - name: Publish mMojo
      run: ant -f ${{ inputs.build-xml-path }} publish ${{ inputs.build-arguments }}
      shell: bash
      env:
        upload_mojo: true
        GITHUB_WORKSPACE: ${{ github.workspace }}
        KRN_MOJO_UPLOAD_REPO: ${{ inputs.repository-name }}
        KRN_REPOSITORY_FILE: "${{ github.workspace }}/mmojo-store/repositories.xml"
    - name: Upload mMojo to store
      working-directory: ./mmojo-store
      run: |
        git config user.name 'Github Action'
        git config user.email 'action@github.com'
        git add mojos.xml
        git add "${{ inputs.mmojo-name}}/*.jar"
        git commit -m "[${{ inputs.mmojo-name }}] Upload ${{ inputs.mmojo-name}}"
        git push
      shell: bash
