on:
  workflow_call:
    inputs:
      krn-core-version:
        default: 0.4.0+20240221-0755
        required: false
        type: string
      build-xml-path:
        default: build.xml
        required: false
        type: string
      build-arguments:
        default: ''
        required: false
        type: string
      mmojo-name:
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      krn-core-repository-url:
        default: ''
        required: false
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0
      - name: Install SW Core, MUnit and KRN Core
        uses: krn-sebastiaan/krn-core@main
        with:
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          krn-core-version: ${{ inputs.krn-core-version }}
          krn-core-repository-url: ${{ inputs.krn-core-repository-url }}
      - name: Create mMojo
        env:
          KRN_CORE_LOCATION: /opt/smallworld/krn_core-${{ inputs.krn-core-version }}
          SMALLWORLD_GIS: /opt/smallworld/core
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: ant -f ${{ inputs.build-xml-path }} make_mojo ${{ inputs.build-arguments }}
      - name: Upload mMojo
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.mmojo-name }}
          path: ${{ inputs.mmojo-name }}*.jar
          if-no-files-found: error
